In [6]:
import numpy as np
import torch
import torch.nn.functional as F

inp = [[ 1.7916e+00, -6.4607e+00, -6.2711e+00, -5.0688e+00, -3.5068e+00,
         -4.0334e+00, -6.6547e+00, -1.7486e+00,  2.0980e+00, -4.1910e+00,
         -5.0029e+00, -2.5206e+00, -5.3439e+00,  1.6036e+01, -2.0640e+00,
         -6.6788e+00,  9.6754e+00, -3.1194e+00, -9.1264e+00],
        [-4.7230e+00, -4.8314e+00, -6.2421e+00, -8.0707e+00, -2.8047e+00,
         -4.0298e+00, -3.0867e+00, -5.0517e+00,  1.4972e+01, -5.1073e+00,
         -1.0896e+01, -4.7347e+00, -5.5322e+00,  8.4725e+00,  2.8774e+00,
         -2.7390e+00, -9.2955e-01, -4.8420e+00, -4.1619e+00],
        [-5.6415e+00, -1.1430e+00,  1.0965e-01, -2.0376e+00, -2.9608e+00,
         -5.0964e+00, -4.4564e+00, -1.4957e+00, -1.6215e+00,  3.9940e+00,
          2.4208e+01,  9.8117e-01, -1.0377e+00, -4.6574e+00, -7.6363e+00,
         -2.7224e+00, -4.3482e+00,  3.5783e+00,  1.9645e+00],
        [-1.7432e+00, -4.3292e+00, -8.8745e+00, -4.9539e+00, -2.2776e+00,
         -2.0945e+00, -6.4223e+00, -2.1612e+00,  4.8467e+00, -3.9070e+00,
         -7.9040e+00, -1.0405e+00, -8.0181e+00,  1.9106e+01, -2.2817e+00,
         -7.9612e+00, -4.7384e+00,  3.1286e+00, -6.3980e+00],
        [-2.4653e+00, -1.3350e+00,  1.5625e+00, -2.8693e+00,  1.5623e-01,
         -1.3528e+00, -2.6597e+00, -6.1386e+00,  6.8572e+00,  2.1972e+00,
          5.2447e+00,  5.9551e-01, -6.4851e+00, -3.6143e+00, -8.1402e+00,
         -6.6327e+00,  3.4065e+00, -1.1001e+00, -2.6091e+00],
        [ 1.7504e+00, -4.5904e+00, -9.9261e+00,  1.3765e+00,  3.0609e+00,
         -2.8950e+00, -1.9981e+00, -3.6916e+00,  7.4108e+00, -5.7256e+00,
         -4.0552e+00, -7.6563e+00, -5.8714e-01, -5.9104e+00, -1.3584e-02,
         -6.6326e-01,  1.9221e+01, -5.1650e+00, -9.3422e+00],
        [-5.3068e+00, -1.4099e+00,  1.6144e+01, -9.3497e-01, -2.2451e+00,
         -2.6051e+00, -2.6956e+00, -5.6708e+00,  5.6067e+00, -1.0935e-01,
         -3.6615e+00, -4.4911e+00, -3.9076e+00, -3.0469e+00, -4.6024e+00,
         -8.3347e+00, -3.7851e+00, -2.9786e+00,  2.2672e+00],
        [-8.5653e+00, -5.3031e+00, -4.8119e+00, -5.7928e+00, -5.0281e+00,
         -3.8339e+00, -5.0812e+00, -3.5136e+00,  1.0287e+00, -4.3853e+00,
         -5.6314e+00, -2.9172e+00, -6.8535e+00,  1.2761e+01, -1.2953e+00,
          4.4617e+00, -2.4294e+00,  1.2141e+01, -6.0321e+00]]
inp = torch.from_numpy(np.array(inp))
print(inp)

tensor([[ 1.7916e+00, -6.4607e+00, -6.2711e+00, -5.0688e+00, -3.5068e+00,
         -4.0334e+00, -6.6547e+00, -1.7486e+00,  2.0980e+00, -4.1910e+00,
         -5.0029e+00, -2.5206e+00, -5.3439e+00,  1.6036e+01, -2.0640e+00,
         -6.6788e+00,  9.6754e+00, -3.1194e+00, -9.1264e+00],
        [-4.7230e+00, -4.8314e+00, -6.2421e+00, -8.0707e+00, -2.8047e+00,
         -4.0298e+00, -3.0867e+00, -5.0517e+00,  1.4972e+01, -5.1073e+00,
         -1.0896e+01, -4.7347e+00, -5.5322e+00,  8.4725e+00,  2.8774e+00,
         -2.7390e+00, -9.2955e-01, -4.8420e+00, -4.1619e+00],
        [-5.6415e+00, -1.1430e+00,  1.0965e-01, -2.0376e+00, -2.9608e+00,
         -5.0964e+00, -4.4564e+00, -1.4957e+00, -1.6215e+00,  3.9940e+00,
          2.4208e+01,  9.8117e-01, -1.0377e+00, -4.6574e+00, -7.6363e+00,
         -2.7224e+00, -4.3482e+00,  3.5783e+00,  1.9645e+00],
        [-1.7432e+00, -4.3292e+00, -8.8745e+00, -4.9539e+00, -2.2776e+00,
         -2.0945e+00, -6.4223e+00, -2.1612e+00,  4.8467e+00, -3.9070e+00,


In [10]:
inp = torch.from_numpy(np.array([-3.6346, -6.9678,  3.0472, -3.9664, -4.5604, -0.5648, -3.5100, -1.4556,
         7.3498, -3.8937, -6.6406, -3.4137, -6.7029, 13.3223, -6.4620, -5.1323,
        -6.5323, -1.0198, -3.5430]))
print(inp)

tensor([-3.6346, -6.9678,  3.0472, -3.9664, -4.5604, -0.5648, -3.5100, -1.4556,
         7.3498, -3.8937, -6.6406, -3.4137, -6.7029, 13.3223, -6.4620, -5.1323,
        -6.5323, -1.0198, -3.5430], dtype=torch.float64)


In [12]:
b = torch.softmax(inp, dim=0)  # 按列SoftMax,列和为1
print(b)

tensor([4.3111e-08, 1.5382e-09, 3.4392e-05, 3.0938e-08, 1.7081e-08, 9.2851e-07,
        4.8832e-08, 3.8099e-07, 2.5413e-03, 3.3271e-08, 2.1335e-09, 5.3768e-08,
        2.0047e-09, 9.9742e-01, 2.5507e-09, 9.6416e-09, 2.3776e-09, 5.8909e-07,
        4.7247e-08], dtype=torch.float64)


In [13]:
torch.max(b, dim=0)

torch.return_types.max(
values=tensor(0.9974, dtype=torch.float64),
indices=tensor(13))

In [4]:
torch.max(inp, dim=1)

TypeError: max() received an invalid combination of arguments - got (list, dim=int), but expected one of:
 * (Tensor input)
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)
